spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
  datasource:
    datasource:
      url: jdbc:postgresql://${DATASOURCE_HOST}/${DATASOURCE_DATABASE}
      username: ${DATASOURCE_USER}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        idleTimeout: 70000
        maxLifetime: 300000
        connectionTimeout: 3000
